Screen:
  screen_width: 1000
  screen_height: 1000
  rows: 100 # Rows and cols of matrix
  cols: 100
  icon_style: 1 # Which style of icons to use
  epochs: 400 # number of days to run the simulation

Population:
  size: Model # Population sizew equals matrix size
  
Infectionmodel:
  states:
      X: S
      E: E
      Y: I
      Z: R
      D: D
      M: M
initialization:
    X: "*"
seed: 42
a: 0 # birth probability
b: 0.0011 # yearly mortality probability
alfa: 0.0010 # yearly mortality probability due to illness
r0: 10 # number of people infected by one peson during illness
de: 5 # number of days being infectious without symptoms
di: 20 # number of days bein ill
dri: 365 # number of days the immunity lasts
p_mortality: 0.02
